// navigation
export const NAVIGATE_CLICK_HOME = "NAVIGATE_CLICK_HOME";
export const SIDEBAR_SELECT_TIMELINE = "SIDEBAR_SELECT_TIMELINE";
export const SIDEBAR_SELECT_CHAT = "SIDEBAR_SELECT_CHAT";

// drafts
export const DRAFTS_CREATE_NEW = "DRAFTS_CREATE_NEW";
export const DRAFTS_DELETE = "DRAFTS_DELETE";
export const DRAFTS_OPEN = "DRAFTS_OPEN";
export const DRAFTS_CREATE_NEW_FOLDER = "DRAFTS_CREATE_NEW_FOLDER";

// editing
export const SET_MODE_WRITE = "SET_MODE_WRITE";
export const SET_MODE_CHAT = "SET_MODE_CHAT";
export const DOCUMENT_CLICK_TITLE = "DOCUMENT_CLICK_TITLE";
export const DOCUMENT_UPDATE_TITLE = "DOCUMENT_UPDATE_TITLE";
export const DOCUMENT_TOGGLE_FORMAT = "DOCUMENT_TOGGLE_FORMAT";
export const DOCUMENT_APPLY_BLOCK_FORMAT = "DOCUMENT_APPLY_BLOCK_FORMAT";
export const DOCUMENT_REVISION_ACCEPT = "DOCUMENT_REVISION_ACCEPT";
export const DOCUMENT_REVISION_DECLINE = "DOCUMENT_REVISION_DECLINE";

//auth
export const SIGNIN_GOOGLE = "SIGNIN_GOOGLE";
export const SIGNIN_EMAIL = "SIGNIN_EMAIL";
export const WAITLIST_SIGNUP = "WAITLIST_SIGNUP";

// chat
export const ASK_AI_SEND_MESSAGE = "ASK_AI_SEND_MESSAGE";
export const ASK_AI_CREATE_NEW_THREAD = "ASK_AI_CREATE_NEW_THREAD";
export const ASK_AI_CHANGE_THREAD = "ASK_AI_CHANGE_THREAD";

// timeline
export const CREATE_COMMENT = "CREATE_COMMENT";
export const COMMENT_AT_MENTION = "COMMENT_AT_MENTION";
export const RESOLVE_COMMENT_THREAD = "RESOLVE_COMMENT_THREAD";
export const REOPEN_COMMENT_THREAD = "REOPEN_COMMENT_THREAD";
export const TIMELINE_SHOW_UPDATE_VERSION = "TIMELINE_SHOW_UPDATE_VERSION";
export const TIMELINE_FLAG_VERSION = "TIMELINE_FLAG_VERSION";
export const TIMELINE_DELETE_FLAGGED_VERSION =
  "TIMELINE_DELETE_FLAGGED_VERSION";
export const TIMELINE_UPDATE_VERSION_SUMMARY =
  "TIMELINE_UPDATE_VERSION_SUMMARY";
export const TIMELINE_UPDATE_COMMENT_SUMMARY =
  "TIMELINE_UPDATE_COMMENT_SUMMARY";

// share modal
export const SHARE_OPEN = "OPEN_SHARE_MODAL";
export const SHARE_CLICK_EDIT_ACCESS = "SHARE_CLICK_EDIT_ACCESS";
export const SHARE_ADD_EMAIL = "SHARE_ADD_EMAIL";
export const SHARE_ADD_CUSTOM_MESSAGE = "SHARE_ADD_CUSTOM_MESSAGE";
export const SHARE_REMOVE_EMAIL = "SHARE_REMOVE_EMAIL";
export const SHARE_SEND_INVITE = "SHARE_SEND_INVITE";
export const SHARE_UPDATE_LINK = "SHARE_UPDATE_LINK";
export const SHARE_REMOVE_EDITOR = "SHARE_REMOVE_EDITOR";

// profile
export const PROFILE_CLICK_AVATAR = "PROFILE_CLICK_AVATAR";
export const PROFILE_OPEN_SETTINGS = "PROFILE_OPEN_SETTINGS";
export const PROFILE_CLICK_COLOR_THEME = "PROFILE_CLICK_COLOR_THEME";
export const PROFILE_CLICK_LOGOUT = "PROFILE_CLICK_LOGOUT";

// payments
export const PAYMENTS_CLICK_CHECKOUT = "PAYMENTS_CLICK_CHECKOUT";

// USER SETTINGS
export const USER_SETTINGS_CLICK_AVATAR = "USER_SETTINGS_CLICK_AVATAR";
export const USER_SETTINGS_UPDATE_NAME = "USER_SETTINGS_UPDATE_NAME";
export const USER_SETTINGS_UPDATE_DISPLAY_NAME =
  "USER_SETTINGS_UPDATE_DISPLAY_NAME";
export const USER_SETTINGS_UPDATE_AVATAR = "USER_SETTINGS_UPDATE_AVATAR";
export const NOTIFICATIONS_SETTINGS_OPEN = "NOTIFICATIONS_SETTINGS_OPEN";
export const NOTIFICATIONS_SETTINGS_UPDATE = "NOTIFICATIONS_SETTINGS_UPDATE";

// AI
export const AI_CLICK_STARTER_PROMPT = "AI_CLICK_STARTER_PROMPT";
export const AI_CLICK_ASK_REVISO = "AI_CLICK_ASK_REVISO";
export const AI_CLICK_EXPLAIN = "AI_CLICK_EXPLAIN";
export const AI_CLICK_ADD_CONTEXT = "AI_CLICK_ADD_CONTEXT";
export const AI_CLICK_CONTEXT_BUTTON = "AI_CLICK_CONTEXT_BUTTON";
export const AI_CONTEXT_UPLOAD_FILE = "AI_CONTEXT_UPLOAD_FILE";
export const AI_CONTEXT_SEARCH = "AI_CONTEXT_SEARCH";
export const AI_CONTEXT_CLICK_ADD_URL = "AI_CONTEXT_CLICK_ADD_URL";
export const AI_CONTEXT_SAVE_URL = "AI_CONTEXT_SAVE_URL";
export const AI_CONTEXT_ADD_FILE = "AI_CONTEXT_ADD_FILE";
export const AI_CONTEXT_ADD_DRAFT = "AI_CONTEXT_ADD_DRAFT";
export const AI_CONTEXT_CLICK_REMOVE_ITEM = "AI_CONTEXT_CLICK_REMOVE_ITEM";
export const AI_SWITCH_LLM = "AI_SWITCH_LLM";
