// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package payments

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/teamreviso/code/pkg/views/layouts"
	"github.com/teamreviso/code/pkg/views/ui"
)

func Successfull() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"w-screen h-screen flex flex-col pt-4 px-9\"><nav class=\"flex items-center\"><div class=\"flex-1\"><a href=\"/\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = ui.Logo().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</a></div></nav><div class=\"mt-20 text-center\"><h1 class=\"text-3xl font-bold\">Payment Successful</h1><div class=\"flex items-center justify-center mt-4 text-lg\"><svg class=\"animate-spin mt-1 -ml-1 mr-3 h-5 w-5 text-white\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\"><circle class=\"opacity-25\" cx=\"12\" cy=\"12\" r=\"10\" stroke=\"currentColor\" stroke-width=\"4\"></circle> <path class=\"opacity-75\" fill=\"currentColor\" d=\"M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z\"></path></svg><div class=\"text-muted-foreground\">Updating your profile...</div></div></div></div><script>\n\t\t  async function checkPaymentStatus() {\n\t\t\ttry {\n\t\t\t  // Get the session_id from the URL\n\t\t\t  const urlParams = new URLSearchParams(window.location.search);\n\t\t\t  const sessionId = urlParams.get('session_id');\n\n\t\t\t  if (!sessionId) {\n\t\t\t\tconsole.error('Session ID not found in the URL');\n\t\t\t\treturn;\n\t\t\t  }\n\n\t\t\t  // Fetch the payment status with the session_id\n\t\t\t  const response = await fetch(`/payments/status?session_id=${sessionId}`);\n\t\t\t  if (response.ok) {\n\t\t\t\tconst data = await response.json();\n\t\t\t\tif (data.status === 'complete') {\n\t\t\t\t  window.location.href = '/drafts';\n\t\t\t\t} else if (data.status === 'error' || data.status === 'failed') {\n\t\t\t\t  window.location.href = '/payments/failure';\n\t\t\t\t}\n\t\t\t  } else {\n\t\t\t\tconsole.error('Error fetching payment status:', response.statusText);\n\t\t\t\twindow.location.href = '/payments/failure';\n\t\t\t  }\n\t\t\t} catch (error) {\n\t\t\t  console.error('Error checking payment status:', error);\n\t\t\t}\n\t\t  }\n\n\t\t  checkPaymentStatus();\n\t\t  // Check the payment status every second\n\t\t  setInterval(checkPaymentStatus, 1000);\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.App("Payment Successful").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
