root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "./build.sh"
  delay = 100
  exclude_dir = ["assets", "checks", "results",  "tmp", "vendor", "testdata", "localdata", "node_modules", "frontend", "pkg/admin/src/node_modules", "rogue/javascript", "pkg/db/migrations", "terraform", "scripts", "pkg/assets/src"]
  exclude_file = []
  exclude_regex = [".*_test.go", ".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 100
  send_interrupt = false
  stop_on_error = true

[color]
  app = "blue"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
