// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package auth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func EmailSent(email string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col items-center mt-[9rem]\"><div class=\"flex justify-center items-center\"><img alt=\"open envelope\" loading=\"lazy\" width=\"120\" height=\"140\" decoding=\"async\" data-nimg=\"1\" class=\"block dark:hidden\" src=\"/static/inboxLight.svg\" style=\"color: transparent;\"> <img alt=\"open envelope\" loading=\"lazy\" width=\"120\" height=\"140\" decoding=\"async\" data-nimg=\"1\" class=\"hidden dark:block\" src=\"/static/inboxDark.svg\" style=\"color: transparent;\"></div><div class=\"flex flex-col justify-center items-center mt-10 \"><h1 class=\"text-3xl font-bold\">Check your email</h1><p class=\"text-center text-lg text-foreground mt-5\"><div>We emailed your magic link to <span class=\"text-violet-500\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(email)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/auth/post_email.templ`, Line: 12, Col: 76}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span>.</div><div>Click the link to log in or sign up.</div><div class=\"mt-5\">Link expires in 15 minutes, so be use to use it soon.</div></p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
