// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameComment = "comments"

// Comment mapped from table <comments>
type Comment struct {
	ID              string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	DocumentID      string         `gorm:"column:document_id;not null" json:"document_id"`
	ThreadID        string         `gorm:"column:thread_id;not null" json:"thread_id"`
	CreatedAt       time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	UserID          string         `gorm:"column:user_id;not null" json:"user_id"`
	Body            string         `gorm:"column:body;not null" json:"body"`
	Selection       *string        `gorm:"column:selection" json:"selection"`
	SelectionStart  *string        `gorm:"column:selection_start" json:"selection_start"`
	SelectionFinish *string        `gorm:"column:selection_finish" json:"selection_finish"`
	Notes           *string        `gorm:"column:notes" json:"notes"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
