// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameDagEdge = "dag_edges"

// DagEdge mapped from table <dag_edges>
type DagEdge struct {
	ID           string    `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	SourceNodeID *string   `gorm:"column:source_node_id" json:"source_node_id"`
	TargetNodeID *string   `gorm:"column:target_node_id" json:"target_node_id"`
	DagID        *string   `gorm:"column:dag_id" json:"dag_id"`
	CreatedAt    time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName DagEdge's table name
func (*DagEdge) TableName() string {
	return TableNameDagEdge
}
