// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: pkg/models/notifications.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommentType int32

const (
	CommentType_UnspecifiedType CommentType = 0
	CommentType_Comment         CommentType = 1
	CommentType_Reply           CommentType = 2 // deprecated
	CommentType_Mention         CommentType = 3
	CommentType_DirectMessage   CommentType = 4
	CommentType_Message         CommentType = 5
)

// Enum value maps for CommentType.
var (
	CommentType_name = map[int32]string{
		0: "UnspecifiedType",
		1: "Comment",
		2: "Reply",
		3: "Mention",
		4: "DirectMessage",
		5: "Message",
	}
	CommentType_value = map[string]int32{
		"UnspecifiedType": 0,
		"Comment":         1,
		"Reply":           2,
		"Mention":         3,
		"DirectMessage":   4,
		"Message":         5,
	}
)

func (x CommentType) Enum() *CommentType {
	p := new(CommentType)
	*p = x
	return p
}

func (x CommentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_models_notifications_proto_enumTypes[0].Descriptor()
}

func (CommentType) Type() protoreflect.EnumType {
	return &file_pkg_models_notifications_proto_enumTypes[0]
}

func (x CommentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentType.Descriptor instead.
func (CommentType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_models_notifications_proto_rawDescGZIP(), []int{0}
}

type NotificationPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*NotificationPayload_Comment
	Value isNotificationPayload_Value `protobuf_oneof:"value"`
}

func (x *NotificationPayload) Reset() {
	*x = NotificationPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_models_notifications_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotificationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPayload) ProtoMessage() {}

func (x *NotificationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_notifications_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPayload.ProtoReflect.Descriptor instead.
func (*NotificationPayload) Descriptor() ([]byte, []int) {
	return file_pkg_models_notifications_proto_rawDescGZIP(), []int{0}
}

func (m *NotificationPayload) GetValue() isNotificationPayload_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *NotificationPayload) GetComment() *MessagingComment {
	if x, ok := x.GetValue().(*NotificationPayload_Comment); ok {
		return x.Comment
	}
	return nil
}

type isNotificationPayload_Value interface {
	isNotificationPayload_Value()
}

type NotificationPayload_Comment struct {
	Comment *MessagingComment `protobuf:"bytes,1,opt,name=comment,proto3,oneof"`
}

func (*NotificationPayload_Comment) isNotificationPayload_Value() {}

type MessagingComment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        CommentType `protobuf:"varint,1,opt,name=type,proto3,enum=models.CommentType" json:"type,omitempty"`
	DocumentId  string      `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ChannelId   string      `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ContainerId string      `protobuf:"bytes,4,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	MessageId   string      `protobuf:"bytes,5,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	AuthorId    string      `protobuf:"bytes,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
}

func (x *MessagingComment) Reset() {
	*x = MessagingComment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_models_notifications_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagingComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagingComment) ProtoMessage() {}

func (x *MessagingComment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_notifications_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagingComment.ProtoReflect.Descriptor instead.
func (*MessagingComment) Descriptor() ([]byte, []int) {
	return file_pkg_models_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *MessagingComment) GetType() CommentType {
	if x != nil {
		return x.Type
	}
	return CommentType_UnspecifiedType
}

func (x *MessagingComment) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *MessagingComment) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *MessagingComment) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *MessagingComment) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessagingComment) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

var File_pkg_models_notifications_proto protoreflect.FileDescriptor

var file_pkg_models_notifications_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0x54, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x34, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xda,
	0x01, 0x0a, 0x10, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x2a, 0x67, 0x0a, 0x0b, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x6e,
	0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x65, 0x6e, 0x74, 0x69,
	0x6f, 0x6e, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x10, 0x05, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x72, 0x65, 0x76, 0x69, 0x73, 0x6f, 0x2f, 0x63, 0x6f,
	0x64, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_models_notifications_proto_rawDescOnce sync.Once
	file_pkg_models_notifications_proto_rawDescData = file_pkg_models_notifications_proto_rawDesc
)

func file_pkg_models_notifications_proto_rawDescGZIP() []byte {
	file_pkg_models_notifications_proto_rawDescOnce.Do(func() {
		file_pkg_models_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_models_notifications_proto_rawDescData)
	})
	return file_pkg_models_notifications_proto_rawDescData
}

var file_pkg_models_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_models_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_models_notifications_proto_goTypes = []any{
	(CommentType)(0),            // 0: models.CommentType
	(*NotificationPayload)(nil), // 1: models.NotificationPayload
	(*MessagingComment)(nil),    // 2: models.MessagingComment
}
var file_pkg_models_notifications_proto_depIdxs = []int32{
	2, // 0: models.NotificationPayload.comment:type_name -> models.MessagingComment
	0, // 1: models.MessagingComment.type:type_name -> models.CommentType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_models_notifications_proto_init() }
func file_pkg_models_notifications_proto_init() {
	if File_pkg_models_notifications_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_models_notifications_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*NotificationPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_models_notifications_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MessagingComment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_models_notifications_proto_msgTypes[0].OneofWrappers = []any{
		(*NotificationPayload_Comment)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_models_notifications_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_models_notifications_proto_goTypes,
		DependencyIndexes: file_pkg_models_notifications_proto_depIdxs,
		EnumInfos:         file_pkg_models_notifications_proto_enumTypes,
		MessageInfos:      file_pkg_models_notifications_proto_msgTypes,
	}.Build()
	File_pkg_models_notifications_proto = out.File
	file_pkg_models_notifications_proto_rawDesc = nil
	file_pkg_models_notifications_proto_goTypes = nil
	file_pkg_models_notifications_proto_depIdxs = nil
}
