// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePaymentHistory = "payment_history"

// PaymentHistory mapped from table <payment_history>
type PaymentHistory struct {
	ID                    string    `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	UserID                string    `gorm:"column:user_id;not null" json:"user_id"`
	StripePaymentIntentID string    `gorm:"column:stripe_payment_intent_id;not null" json:"stripe_payment_intent_id"`
	AmountCents           int32     `gorm:"column:amount_cents;not null" json:"amount_cents"`
	Currency              string    `gorm:"column:currency;not null;default:USD" json:"currency"`
	Status                string    `gorm:"column:status;not null" json:"status"`
	CreatedAt             time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName PaymentHistory's table name
func (*PaymentHistory) TableName() string {
	return TableNamePaymentHistory
}
