// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePrompt = "prompts"

// Prompt mapped from table <prompts>
type Prompt struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PromptName    string    `gorm:"column:prompt_name;not null" json:"prompt_name"`
	SystemContent *string   `gorm:"column:system_content" json:"system_content"`
	Version       string    `gorm:"column:version;not null;default:''::text" json:"version"`
	Provider      string    `gorm:"column:provider;not null" json:"provider"`
	ModelName     string    `gorm:"column:model_name;not null" json:"model_name"`
	Temperature   float64   `gorm:"column:temperature;default:1.0" json:"temperature"`
	MaxTokens     int32     `gorm:"column:max_tokens" json:"max_tokens"`
	TopP          float64   `gorm:"column:top_p;default:1.0" json:"top_p"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	ContentJSON   string    `gorm:"column:content_json" json:"content_json"`
}

// TableName Prompt's table name
func (*Prompt) TableName() string {
	return TableNamePrompt
}
