// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSharedDocumentLink = "shared_document_links"

// SharedDocumentLink mapped from table <shared_document_links>
type SharedDocumentLink struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DocumentID   string    `gorm:"column:document_id;not null" json:"document_id"`
	InviterID    string    `gorm:"column:inviter_id;not null" json:"inviter_id"`
	InviteeEmail string    `gorm:"column:invitee_email;not null" json:"invitee_email"`
	InviteLink   string    `gorm:"column:invite_link;not null;default:generate_default_invite_link()" json:"invite_link"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	IsActive     bool      `gorm:"column:is_active;default:true" json:"is_active"`
}

// TableName SharedDocumentLink's table name
func (*SharedDocumentLink) TableName() string {
	return TableNameSharedDocumentLink
}
