// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID               string    `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	Name             string    `gorm:"column:name;not null" json:"name"`
	Email            string    `gorm:"column:email;not null" json:"email"`
	PasswordHash     string    `gorm:"column:password_hash" json:"password_hash"`
	Provider         string    `gorm:"column:provider;not null" json:"provider"`
	CreatedAt        time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	Picture          *string   `gorm:"column:picture" json:"picture"`
	Admin            bool      `gorm:"column:admin;not null" json:"admin"`
	DisplayName      string    `gorm:"column:display_name;not null" json:"display_name"`
	Educator         bool      `gorm:"column:educator;not null" json:"educator"`
	StripeCustomerID string    `gorm:"column:stripe_customer_id" json:"stripe_customer_id"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
