// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package utils

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Redirect(url string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_Redirect_316d`,
		Function: `function __templ_Redirect_316d(url){window.location = url
}`,
		Call:       templ.SafeScript(`__templ_Redirect_316d`, url),
		CallInline: templ.SafeScriptInline(`__templ_Redirect_316d`, url),
	}
}

var _ = templruntime.GeneratedTemplate
