// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: pkg/background/wire/wire.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProactiveAiMessageType int32

const (
	ProactiveAiMessageType_PROACTIVE_AI_MESSAGE_TYPE_NEW_DOCUMENT   ProactiveAiMessageType = 0
	ProactiveAiMessageType_PROACTIVE_AI_MESSAGE_TYPE_PASTE_RESPONSE ProactiveAiMessageType = 1
)

// Enum value maps for ProactiveAiMessageType.
var (
	ProactiveAiMessageType_name = map[int32]string{
		0: "PROACTIVE_AI_MESSAGE_TYPE_NEW_DOCUMENT",
		1: "PROACTIVE_AI_MESSAGE_TYPE_PASTE_RESPONSE",
	}
	ProactiveAiMessageType_value = map[string]int32{
		"PROACTIVE_AI_MESSAGE_TYPE_NEW_DOCUMENT":   0,
		"PROACTIVE_AI_MESSAGE_TYPE_PASTE_RESPONSE": 1,
	}
)

func (x ProactiveAiMessageType) Enum() *ProactiveAiMessageType {
	p := new(ProactiveAiMessageType)
	*p = x
	return p
}

func (x ProactiveAiMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProactiveAiMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_background_wire_wire_proto_enumTypes[0].Descriptor()
}

func (ProactiveAiMessageType) Type() protoreflect.EnumType {
	return &file_pkg_background_wire_wire_proto_enumTypes[0]
}

func (x ProactiveAiMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProactiveAiMessageType.Descriptor instead.
func (ProactiveAiMessageType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{0}
}

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{0}
}

type AccessDoc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocId        string `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	TimestampStr string `protobuf:"bytes,3,opt,name=timestamp_str,json=timestampStr,proto3" json:"timestamp_str,omitempty"`
}

func (x *AccessDoc) Reset() {
	*x = AccessDoc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessDoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessDoc) ProtoMessage() {}

func (x *AccessDoc) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessDoc.ProtoReflect.Descriptor instead.
func (*AccessDoc) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{1}
}

func (x *AccessDoc) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccessDoc) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *AccessDoc) GetTimestampStr() string {
	if x != nil {
		return x.TimestampStr
	}
	return ""
}

type NotifyChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatorId   string `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	DocId       string `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	ChannelId   string `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ContainerId string `protobuf:"bytes,4,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	MessageId   string `protobuf:"bytes,5,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
}

func (x *NotifyChannel) Reset() {
	*x = NotifyChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyChannel) ProtoMessage() {}

func (x *NotifyChannel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyChannel.ProtoReflect.Descriptor instead.
func (*NotifyChannel) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyChannel) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *NotifyChannel) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *NotifyChannel) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *NotifyChannel) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *NotifyChannel) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type RespondToMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocId      string `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	ThreadId   string `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	MessageId  string `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ResponseId string `protobuf:"bytes,4,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
}

func (x *RespondToMessage) Reset() {
	*x = RespondToMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespondToMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToMessage) ProtoMessage() {}

func (x *RespondToMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToMessage.ProtoReflect.Descriptor instead.
func (*RespondToMessage) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{3}
}

func (x *RespondToMessage) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *RespondToMessage) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *RespondToMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RespondToMessage) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

type RespondToThread struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocId           string `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	ThreadId        string `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	UserId          string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthorId        string `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	InputMessageId  string `protobuf:"bytes,5,opt,name=input_message_id,json=inputMessageId,proto3" json:"input_message_id,omitempty"`
	OutputMessageId string `protobuf:"bytes,6,opt,name=output_message_id,json=outputMessageId,proto3" json:"output_message_id,omitempty"`
}

func (x *RespondToThread) Reset() {
	*x = RespondToThread{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespondToThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToThread) ProtoMessage() {}

func (x *RespondToThread) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToThread.ProtoReflect.Descriptor instead.
func (*RespondToThread) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{4}
}

func (x *RespondToThread) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *RespondToThread) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *RespondToThread) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RespondToThread) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *RespondToThread) GetInputMessageId() string {
	if x != nil {
		return x.InputMessageId
	}
	return ""
}

func (x *RespondToThread) GetOutputMessageId() string {
	if x != nil {
		return x.OutputMessageId
	}
	return ""
}

type ProactiveAiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        ProactiveAiMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=wire.ProactiveAiMessageType" json:"type,omitempty"`
	DocId       string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	ContainerId string                 `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	MessageId   string                 `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ThreadId    string                 `protobuf:"bytes,5,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
}

func (x *ProactiveAiMessage) Reset() {
	*x = ProactiveAiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProactiveAiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProactiveAiMessage) ProtoMessage() {}

func (x *ProactiveAiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProactiveAiMessage.ProtoReflect.Descriptor instead.
func (*ProactiveAiMessage) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{5}
}

func (x *ProactiveAiMessage) GetType() ProactiveAiMessageType {
	if x != nil {
		return x.Type
	}
	return ProactiveAiMessageType_PROACTIVE_AI_MESSAGE_TYPE_NEW_DOCUMENT
}

func (x *ProactiveAiMessage) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *ProactiveAiMessage) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ProactiveAiMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ProactiveAiMessage) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type ScreenshotAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScreenshotAll) Reset() {
	*x = ScreenshotAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScreenshotAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotAll) ProtoMessage() {}

func (x *ScreenshotAll) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotAll.ProtoReflect.Descriptor instead.
func (*ScreenshotAll) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{6}
}

type Screenshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocId string `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
}

func (x *Screenshot) Reset() {
	*x = Screenshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Screenshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screenshot) ProtoMessage() {}

func (x *Screenshot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screenshot.ProtoReflect.Descriptor instead.
func (*Screenshot) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{7}
}

func (x *Screenshot) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type SendEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From     string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To       string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Subject  string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Txtbody  string `protobuf:"bytes,4,opt,name=txtbody,proto3" json:"txtbody,omitempty"`
	Htmlbody string `protobuf:"bytes,5,opt,name=htmlbody,proto3" json:"htmlbody,omitempty"`
}

func (x *SendEmail) Reset() {
	*x = SendEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmail) ProtoMessage() {}

func (x *SendEmail) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmail.ProtoReflect.Descriptor instead.
func (*SendEmail) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{8}
}

func (x *SendEmail) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendEmail) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendEmail) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmail) GetTxtbody() string {
	if x != nil {
		return x.Txtbody
	}
	return ""
}

func (x *SendEmail) GetHtmlbody() string {
	if x != nil {
		return x.Htmlbody
	}
	return ""
}

type SendFirstOpen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToUserId string `protobuf:"bytes,1,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	ReaderId string `protobuf:"bytes,2,opt,name=reader_id,json=readerId,proto3" json:"reader_id,omitempty"`
	DocId    string `protobuf:"bytes,3,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
}

func (x *SendFirstOpen) Reset() {
	*x = SendFirstOpen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFirstOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFirstOpen) ProtoMessage() {}

func (x *SendFirstOpen) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFirstOpen.ProtoReflect.Descriptor instead.
func (*SendFirstOpen) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{9}
}

func (x *SendFirstOpen) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *SendFirstOpen) GetReaderId() string {
	if x != nil {
		return x.ReaderId
	}
	return ""
}

func (x *SendFirstOpen) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type SnapshotRogue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocId string `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
}

func (x *SnapshotRogue) Reset() {
	*x = SnapshotRogue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRogue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRogue) ProtoMessage() {}

func (x *SnapshotRogue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRogue.ProtoReflect.Descriptor instead.
func (*SnapshotRogue) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{10}
}

func (x *SnapshotRogue) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type SnapshotAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *SnapshotAll) Reset() {
	*x = SnapshotAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotAll) ProtoMessage() {}

func (x *SnapshotAll) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotAll.ProtoReflect.Descriptor instead.
func (*SnapshotAll) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{11}
}

func (x *SnapshotAll) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RunDag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dag   string            `protobuf:"bytes,1,opt,name=dag,proto3" json:"dag,omitempty"`
	State map[string]string `protobuf:"bytes,2,rep,name=state,proto3" json:"state,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *RunDag) Reset() {
	*x = RunDag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunDag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunDag) ProtoMessage() {}

func (x *RunDag) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunDag.ProtoReflect.Descriptor instead.
func (*RunDag) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{12}
}

func (x *RunDag) GetDag() string {
	if x != nil {
		return x.Dag
	}
	return ""
}

func (x *RunDag) GetState() map[string]string {
	if x != nil {
		return x.State
	}
	return nil
}

type SummarizeSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocId           string `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	SessionId       string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId          string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastMessageTime int64  `protobuf:"varint,5,opt,name=last_message_time,json=lastMessageTime,proto3" json:"last_message_time,omitempty"`
}

func (x *SummarizeSession) Reset() {
	*x = SummarizeSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummarizeSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeSession) ProtoMessage() {}

func (x *SummarizeSession) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeSession.ProtoReflect.Descriptor instead.
func (*SummarizeSession) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{13}
}

func (x *SummarizeSession) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *SummarizeSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SummarizeSession) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SummarizeSession) GetLastMessageTime() int64 {
	if x != nil {
		return x.LastMessageTime
	}
	return 0
}

type SummarizeCommentThread struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocId         string `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	EventId       string `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ThreadEventId string `protobuf:"bytes,3,opt,name=thread_event_id,json=threadEventId,proto3" json:"thread_event_id,omitempty"`
}

func (x *SummarizeCommentThread) Reset() {
	*x = SummarizeCommentThread{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummarizeCommentThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeCommentThread) ProtoMessage() {}

func (x *SummarizeCommentThread) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeCommentThread.ProtoReflect.Descriptor instead.
func (*SummarizeCommentThread) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{14}
}

func (x *SummarizeCommentThread) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *SummarizeCommentThread) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SummarizeCommentThread) GetThreadEventId() string {
	if x != nil {
		return x.ThreadEventId
	}
	return ""
}

type NotifyNewTimelineComment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocId          string   `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	EventId        string   `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ExcludeUserIds []string `protobuf:"bytes,3,rep,name=exclude_user_ids,json=excludeUserIds,proto3" json:"exclude_user_ids,omitempty"`
}

func (x *NotifyNewTimelineComment) Reset() {
	*x = NotifyNewTimelineComment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyNewTimelineComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewTimelineComment) ProtoMessage() {}

func (x *NotifyNewTimelineComment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewTimelineComment.ProtoReflect.Descriptor instead.
func (*NotifyNewTimelineComment) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{15}
}

func (x *NotifyNewTimelineComment) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *NotifyNewTimelineComment) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *NotifyNewTimelineComment) GetExcludeUserIds() []string {
	if x != nil {
		return x.ExcludeUserIds
	}
	return nil
}

type NotifyNewMentionShare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocId       string `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	EventId     string `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RecipientId string `protobuf:"bytes,3,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
}

func (x *NotifyNewMentionShare) Reset() {
	*x = NotifyNewMentionShare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyNewMentionShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewMentionShare) ProtoMessage() {}

func (x *NotifyNewMentionShare) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewMentionShare.ProtoReflect.Descriptor instead.
func (*NotifyNewMentionShare) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{16}
}

func (x *NotifyNewMentionShare) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *NotifyNewMentionShare) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *NotifyNewMentionShare) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

type NotifyFirstOpen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocId    string `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	ReaderId string `protobuf:"bytes,2,opt,name=reader_id,json=readerId,proto3" json:"reader_id,omitempty"`
}

func (x *NotifyFirstOpen) Reset() {
	*x = NotifyFirstOpen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_background_wire_wire_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyFirstOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyFirstOpen) ProtoMessage() {}

func (x *NotifyFirstOpen) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_background_wire_wire_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyFirstOpen.ProtoReflect.Descriptor instead.
func (*NotifyFirstOpen) Descriptor() ([]byte, []int) {
	return file_pkg_background_wire_wire_proto_rawDescGZIP(), []int{17}
}

func (x *NotifyFirstOpen) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *NotifyFirstOpen) GetReaderId() string {
	if x != nil {
		return x.ReaderId
	}
	return ""
}

var File_pkg_background_wire_wire_proto protoreflect.FileDescriptor

var file_pkg_background_wire_wire_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x2f, 0x77, 0x69, 0x72, 0x65, 0x2f, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x77, 0x69, 0x72, 0x65, 0x22, 0x06, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x22, 0x60,
	0x0a, 0x09, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x44, 0x6f, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x6f, 0x63, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x53, 0x74, 0x72,
	0x22, 0xa6, 0x01, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49,
	0x64, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x64, 0x6f, 0x63, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x86, 0x01, 0x0a, 0x10, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x64, 0x54, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x15,
	0x0a, 0x06, 0x64, 0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x64, 0x6f, 0x63, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x49, 0x64, 0x22, 0xd1, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x54, 0x6f,
	0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x6f, 0x63, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x28, 0x0a, 0x10, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0xbc, 0x01, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x41, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x77, 0x69,
	0x72, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x41, 0x69, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x15, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x64, 0x6f, 0x63, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x68, 0x72, 0x65,
	0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x68, 0x72,
	0x65, 0x61, 0x64, 0x49, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73,
	0x68, 0x6f, 0x74, 0x41, 0x6c, 0x6c, 0x22, 0x23, 0x0a, 0x0a, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e,
	0x73, 0x68, 0x6f, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x6f, 0x63, 0x49, 0x64, 0x22, 0x7f, 0x0a, 0x09, 0x53,
	0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x78, 0x74, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x78, 0x74, 0x62, 0x6f, 0x64, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x74, 0x6d, 0x6c, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x68, 0x74, 0x6d, 0x6c, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x61, 0x0a, 0x0d,
	0x53, 0x65, 0x6e, 0x64, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x1c, 0x0a,
	0x0a, 0x74, 0x6f, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x6f, 0x63, 0x49, 0x64, 0x22,
	0x26, 0x0a, 0x0d, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x6f, 0x67, 0x75, 0x65,
	0x12, 0x15, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x64, 0x6f, 0x63, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x0b, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x83, 0x01, 0x0a, 0x06, 0x52, 0x75, 0x6e, 0x44, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x67, 0x12, 0x2d, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x77,
	0x69, 0x72, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x44, 0x61, 0x67, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x38, 0x0a, 0x0a,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x9c, 0x01, 0x0a, 0x10, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x69, 0x7a, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x64,
	0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x6f, 0x63,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x4a, 0x04, 0x08, 0x04, 0x10, 0x05, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x72, 0x0a, 0x16, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69,
	0x7a, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x12,
	0x15, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x64, 0x6f, 0x63, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x68, 0x72, 0x65,
	0x61, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x76, 0x0a, 0x18, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x4e, 0x65, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x6f, 0x63, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x65, 0x78, 0x63, 0x6c, 0x75,
	0x64, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0e, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x73, 0x22, 0x6c, 0x0a, 0x15, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4e, 0x65, 0x77, 0x4d, 0x65,
	0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x6f,
	0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x6f, 0x63, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x45, 0x0a, 0x0f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4f, 0x70,
	0x65, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x64, 0x6f, 0x63, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x49, 0x64, 0x2a, 0x72, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x41, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x2a, 0x0a, 0x26, 0x50, 0x52, 0x4f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x5f, 0x41, 0x49,
	0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x45,
	0x57, 0x5f, 0x44, 0x4f, 0x43, 0x55, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x2c, 0x0a, 0x28,
	0x50, 0x52, 0x4f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x5f, 0x41, 0x49, 0x5f, 0x4d, 0x45, 0x53,
	0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x41, 0x53, 0x54, 0x45, 0x5f,
	0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x01, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x72, 0x65, 0x76,
	0x69, 0x73, 0x6f, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x62, 0x61, 0x63,
	0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2f, 0x77, 0x69, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_background_wire_wire_proto_rawDescOnce sync.Once
	file_pkg_background_wire_wire_proto_rawDescData = file_pkg_background_wire_wire_proto_rawDesc
)

func file_pkg_background_wire_wire_proto_rawDescGZIP() []byte {
	file_pkg_background_wire_wire_proto_rawDescOnce.Do(func() {
		file_pkg_background_wire_wire_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_background_wire_wire_proto_rawDescData)
	})
	return file_pkg_background_wire_wire_proto_rawDescData
}

var file_pkg_background_wire_wire_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_background_wire_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_pkg_background_wire_wire_proto_goTypes = []any{
	(ProactiveAiMessageType)(0),      // 0: wire.ProactiveAiMessageType
	(*Ping)(nil),                     // 1: wire.Ping
	(*AccessDoc)(nil),                // 2: wire.AccessDoc
	(*NotifyChannel)(nil),            // 3: wire.NotifyChannel
	(*RespondToMessage)(nil),         // 4: wire.RespondToMessage
	(*RespondToThread)(nil),          // 5: wire.RespondToThread
	(*ProactiveAiMessage)(nil),       // 6: wire.ProactiveAiMessage
	(*ScreenshotAll)(nil),            // 7: wire.ScreenshotAll
	(*Screenshot)(nil),               // 8: wire.Screenshot
	(*SendEmail)(nil),                // 9: wire.SendEmail
	(*SendFirstOpen)(nil),            // 10: wire.SendFirstOpen
	(*SnapshotRogue)(nil),            // 11: wire.SnapshotRogue
	(*SnapshotAll)(nil),              // 12: wire.SnapshotAll
	(*RunDag)(nil),                   // 13: wire.RunDag
	(*SummarizeSession)(nil),         // 14: wire.SummarizeSession
	(*SummarizeCommentThread)(nil),   // 15: wire.SummarizeCommentThread
	(*NotifyNewTimelineComment)(nil), // 16: wire.NotifyNewTimelineComment
	(*NotifyNewMentionShare)(nil),    // 17: wire.NotifyNewMentionShare
	(*NotifyFirstOpen)(nil),          // 18: wire.NotifyFirstOpen
	nil,                              // 19: wire.RunDag.StateEntry
}
var file_pkg_background_wire_wire_proto_depIdxs = []int32{
	0,  // 0: wire.ProactiveAiMessage.type:type_name -> wire.ProactiveAiMessageType
	19, // 1: wire.RunDag.state:type_name -> wire.RunDag.StateEntry
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_background_wire_wire_proto_init() }
func file_pkg_background_wire_wire_proto_init() {
	if File_pkg_background_wire_wire_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_background_wire_wire_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AccessDoc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*NotifyChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RespondToMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RespondToThread); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ProactiveAiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ScreenshotAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Screenshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*SendEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SendFirstOpen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*SnapshotRogue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*SnapshotAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*RunDag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*SummarizeSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*SummarizeCommentThread); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*NotifyNewTimelineComment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*NotifyNewMentionShare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_background_wire_wire_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*NotifyFirstOpen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_background_wire_wire_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_background_wire_wire_proto_goTypes,
		DependencyIndexes: file_pkg_background_wire_wire_proto_depIdxs,
		EnumInfos:         file_pkg_background_wire_wire_proto_enumTypes,
		MessageInfos:      file_pkg_background_wire_wire_proto_msgTypes,
	}.Build()
	File_pkg_background_wire_wire_proto = out.File
	file_pkg_background_wire_wire_proto_rawDesc = nil
	file_pkg_background_wire_wire_proto_goTypes = nil
	file_pkg_background_wire_wire_proto_depIdxs = nil
}
