// navigation
export const NAVIGATE_CLICK_HOME = "NAVIGATE_CLICK_HOME";

// documents
export const DOCUMENTS_CREATE_NEW = "DOCUMENTS_CREATE_NEW";
export const DOCUMENTS_DELETE = "DOCUMENTS_DELETE";
export const DOCUMENTE_DELETE_CONFIRM = "DOCUMENTS_DELETE_CONFIRM";
export const DOCUMENTS_OPEN = "DOCUMENTS_OPEN";
export const DOCUMENTS_OPEN_DOC_MENU = "DOCUMENTS_OPEN_DOC_MENU";

// editing
export const SET_MODE_WRITE = "SET_MODE_WRITE";
export const SET_MODE_CHAT = "SET_MODE_CHAT";
export const DOCUMENT_CLICK_TITLE = "DOCUMENT_CLICK_TITLE";
export const DOCUMENT_UPDATE_TITLE = "DOCUMENT_UPDATE_TITLE";
export const DOCUMENT_TOGGLE_FORMAT = "DOCUMENT_TOGGLE_FORMAT";
export const DOCUMENT_APPLY_BLOCK_FORMAT = "DOCUMENT_APPLY_BLOCK_FORMAT";

//auth
export const SIGNIN_GOOGLE = "SIGNIN_GOOGLE";
export const SIGNIN_EMAIL = "SIGNIN_EMAIL";
export const WAITLIST_SIGNUP = "WAITLIST_SIGNUP";

// chat
export const CHAT_SEND_MESSAGE = "CHATE_SEND_MESSAGE";
export const CHAT_CLICK_CHANNEL = "CHAT_CLICK_CHANNEL";
export const CHAT_CLICK_REPLACE = "CHAT_CLICK_REPLACE";
export const CHAT_CLICK_REVERT = "CHAT_CLICK_REVERT";
export const CHAT_CLICK_INSERT_BELOW = "CHAT_CLICK_INSERT_BELOW";
export const CHAT_CLICK_COPY_SUGGESTION = "CHAT_CLICK_COPY_SUGGESTION";
export const CHAT_CLICK_COPY_MESSAGE = "CHAT_CLICK_COPY_MESSAGE";
export const CHAT_CLICK_ADD_TO_DOCUMENT = "CHAT_CLICK_ADD_TO_DOCUMENT";
export const CHAT_CLICK_INVITE_WRITER = "CHAT_CLICK_INVITE_WRITER";
export const CHAT_CLICK_REGENERATE = "CHAT_CLICK_REGENERATE";

// share modal
export const SHARE_OPEN = "OPEN_SHARE_MODAL";
export const SHARE_CLICK_EDIT_ACCESS = "SHARE_CLICK_EDIT_ACCESS";
export const SHARE_ADD_EMAIL = "SHARE_ADD_EMAIL";
export const SHARE_ADD_CUSTOM_MESSAGE = "SHARE_ADD_CUSTOM_MESSAGE";
export const SHARE_REMOVE_EMAIL = "SHARE_REMOVE_EMAIL";
export const SHARE_SEND_INVITE = "SHARE_SEND_INVITE";
export const SHARE_UPDATE_LINK = "SHARE_UPDATE_LINK";
export const SHARE_REMOVE_EDITOR = "SHARE_REMOVE_EDITOR";

// profile
export const PROFILE_CLICK_AVATAR = "PROFILE_CLICK_AVATAR";
export const PROFILE_OPEN_SETTINGS = "PROFILE_OPEN_SETTINGS";
export const PROFILE_CLICK_COLOR_THEME = "PROFILE_CLICK_COLOR_THEME";
export const PROFILE_CLICK_LOGOUT = "PROFILE_CLICK_LOGOUT";

// USER SETTINGS
export const USER_SETTINGS_CLICK_AVATAR = "USER_SETTINGS_CLICK_AVATAR";
export const USER_SETTINGS_UPDATE_NAME = "USER_SETTINGS_UPDATE_NAME";
export const USER_SETTINGS_UPDATE_DISPLAY_NAME =
  "USER_SETTINGS_UPDATE_DISPLAY_NAME";
export const USER_SETTINGS_UPDATE_AVATAR = "USER_SETTINGS_UPDATE_AVATAR";

// AI
export const AI_CLICK_STARTER_PROMPT = "AI_CLICK_STARTER_PROMPT";
export const AI_CLICK_ASK_REVISO = "AI_CLICK_ASK_REVISO";
